version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: alpha-portainer
    restart: always
    ports:
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  alpha_amp-mariadb:
    image: mariadb:10.3.7
    # volumes:
    #     - ~/volumes/jhipster/alpha_amp/mysql/:/var/lib/mysql/
    environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_DATABASE=alpha_amp
    ports:
        - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  alpha_amp-mariadb:
    image: mariadb:10.3.7
    # volumes:
    #     - ~/volumes/jhipster/alpha_amp/mysql/:/var/lib/mysql/
    environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=alpha_amp
    ports:
        - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

networks:

  elk:
    driver: bridge
